# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/timothysmith/Code/Booster

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/timothysmith/Code/Booster

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/timothysmith/Code/Booster/CMakeFiles /Users/timothysmith/Code/Booster/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/timothysmith/Code/Booster/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ChallengeServer

# Build rule for target.
ChallengeServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ChallengeServer
.PHONY : ChallengeServer

# fast build rule for target.
ChallengeServer/fast:
	$(MAKE) -f CMakeFiles/ChallengeServer.dir/build.make CMakeFiles/ChallengeServer.dir/build
.PHONY : ChallengeServer/fast

#=============================================================================
# Target rules for targets named ASIOTimers

# Build rule for target.
ASIOTimers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ASIOTimers
.PHONY : ASIOTimers

# fast build rule for target.
ASIOTimers/fast:
	$(MAKE) -f CMakeFiles/ASIOTimers.dir/build.make CMakeFiles/ASIOTimers.dir/build
.PHONY : ASIOTimers/fast

#=============================================================================
# Target rules for targets named SynchronousClient

# Build rule for target.
SynchronousClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SynchronousClient
.PHONY : SynchronousClient

# fast build rule for target.
SynchronousClient/fast:
	$(MAKE) -f CMakeFiles/SynchronousClient.dir/build.make CMakeFiles/SynchronousClient.dir/build
.PHONY : SynchronousClient/fast

#=============================================================================
# Target rules for targets named ASIOExceptions

# Build rule for target.
ASIOExceptions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ASIOExceptions
.PHONY : ASIOExceptions

# fast build rule for target.
ASIOExceptions/fast:
	$(MAKE) -f CMakeFiles/ASIOExceptions.dir/build.make CMakeFiles/ASIOExceptions.dir/build
.PHONY : ASIOExceptions/fast

#=============================================================================
# Target rules for targets named ASIOTutorial

# Build rule for target.
ASIOTutorial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ASIOTutorial
.PHONY : ASIOTutorial

# fast build rule for target.
ASIOTutorial/fast:
	$(MAKE) -f CMakeFiles/ASIOTutorial.dir/build.make CMakeFiles/ASIOTutorial.dir/build
.PHONY : ASIOTutorial/fast

#=============================================================================
# Target rules for targets named IOServiceWork

# Build rule for target.
IOServiceWork: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IOServiceWork
.PHONY : IOServiceWork

# fast build rule for target.
IOServiceWork/fast:
	$(MAKE) -f CMakeFiles/IOServiceWork.dir/build.make CMakeFiles/IOServiceWork.dir/build
.PHONY : IOServiceWork/fast

#=============================================================================
# Target rules for targets named BindTutorial

# Build rule for target.
BindTutorial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BindTutorial
.PHONY : BindTutorial

# fast build rule for target.
BindTutorial/fast:
	$(MAKE) -f CMakeFiles/BindTutorial.dir/build.make CMakeFiles/BindTutorial.dir/build
.PHONY : BindTutorial/fast

#=============================================================================
# Target rules for targets named IOService

# Build rule for target.
IOService: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IOService
.PHONY : IOService

# fast build rule for target.
IOService/fast:
	$(MAKE) -f CMakeFiles/IOService.dir/build.make CMakeFiles/IOService.dir/build
.PHONY : IOService/fast

#=============================================================================
# Target rules for targets named Booster

# Build rule for target.
Booster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Booster
.PHONY : Booster

# fast build rule for target.
Booster/fast:
	$(MAKE) -f CMakeFiles/Booster.dir/build.make CMakeFiles/Booster.dir/build
.PHONY : Booster/fast

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

#=============================================================================
# Target rules for targets named AsynchronousClient

# Build rule for target.
AsynchronousClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AsynchronousClient
.PHONY : AsynchronousClient

# fast build rule for target.
AsynchronousClient/fast:
	$(MAKE) -f CMakeFiles/AsynchronousClient.dir/build.make CMakeFiles/AsynchronousClient.dir/build
.PHONY : AsynchronousClient/fast

BookTutorial/ASIOExceptions.o: BookTutorial/ASIOExceptions.cpp.o

.PHONY : BookTutorial/ASIOExceptions.o

# target to build an object file
BookTutorial/ASIOExceptions.cpp.o:
	$(MAKE) -f CMakeFiles/ASIOExceptions.dir/build.make CMakeFiles/ASIOExceptions.dir/BookTutorial/ASIOExceptions.cpp.o
.PHONY : BookTutorial/ASIOExceptions.cpp.o

BookTutorial/ASIOExceptions.i: BookTutorial/ASIOExceptions.cpp.i

.PHONY : BookTutorial/ASIOExceptions.i

# target to preprocess a source file
BookTutorial/ASIOExceptions.cpp.i:
	$(MAKE) -f CMakeFiles/ASIOExceptions.dir/build.make CMakeFiles/ASIOExceptions.dir/BookTutorial/ASIOExceptions.cpp.i
.PHONY : BookTutorial/ASIOExceptions.cpp.i

BookTutorial/ASIOExceptions.s: BookTutorial/ASIOExceptions.cpp.s

.PHONY : BookTutorial/ASIOExceptions.s

# target to generate assembly for a file
BookTutorial/ASIOExceptions.cpp.s:
	$(MAKE) -f CMakeFiles/ASIOExceptions.dir/build.make CMakeFiles/ASIOExceptions.dir/BookTutorial/ASIOExceptions.cpp.s
.PHONY : BookTutorial/ASIOExceptions.cpp.s

BookTutorial/ASIOTimers.o: BookTutorial/ASIOTimers.cpp.o

.PHONY : BookTutorial/ASIOTimers.o

# target to build an object file
BookTutorial/ASIOTimers.cpp.o:
	$(MAKE) -f CMakeFiles/ASIOTimers.dir/build.make CMakeFiles/ASIOTimers.dir/BookTutorial/ASIOTimers.cpp.o
.PHONY : BookTutorial/ASIOTimers.cpp.o

BookTutorial/ASIOTimers.i: BookTutorial/ASIOTimers.cpp.i

.PHONY : BookTutorial/ASIOTimers.i

# target to preprocess a source file
BookTutorial/ASIOTimers.cpp.i:
	$(MAKE) -f CMakeFiles/ASIOTimers.dir/build.make CMakeFiles/ASIOTimers.dir/BookTutorial/ASIOTimers.cpp.i
.PHONY : BookTutorial/ASIOTimers.cpp.i

BookTutorial/ASIOTimers.s: BookTutorial/ASIOTimers.cpp.s

.PHONY : BookTutorial/ASIOTimers.s

# target to generate assembly for a file
BookTutorial/ASIOTimers.cpp.s:
	$(MAKE) -f CMakeFiles/ASIOTimers.dir/build.make CMakeFiles/ASIOTimers.dir/BookTutorial/ASIOTimers.cpp.s
.PHONY : BookTutorial/ASIOTimers.cpp.s

BookTutorial/ASIOTutorial.o: BookTutorial/ASIOTutorial.cpp.o

.PHONY : BookTutorial/ASIOTutorial.o

# target to build an object file
BookTutorial/ASIOTutorial.cpp.o:
	$(MAKE) -f CMakeFiles/ASIOTutorial.dir/build.make CMakeFiles/ASIOTutorial.dir/BookTutorial/ASIOTutorial.cpp.o
.PHONY : BookTutorial/ASIOTutorial.cpp.o

BookTutorial/ASIOTutorial.i: BookTutorial/ASIOTutorial.cpp.i

.PHONY : BookTutorial/ASIOTutorial.i

# target to preprocess a source file
BookTutorial/ASIOTutorial.cpp.i:
	$(MAKE) -f CMakeFiles/ASIOTutorial.dir/build.make CMakeFiles/ASIOTutorial.dir/BookTutorial/ASIOTutorial.cpp.i
.PHONY : BookTutorial/ASIOTutorial.cpp.i

BookTutorial/ASIOTutorial.s: BookTutorial/ASIOTutorial.cpp.s

.PHONY : BookTutorial/ASIOTutorial.s

# target to generate assembly for a file
BookTutorial/ASIOTutorial.cpp.s:
	$(MAKE) -f CMakeFiles/ASIOTutorial.dir/build.make CMakeFiles/ASIOTutorial.dir/BookTutorial/ASIOTutorial.cpp.s
.PHONY : BookTutorial/ASIOTutorial.cpp.s

BookTutorial/AsyncThreadGroup.o: BookTutorial/AsyncThreadGroup.cpp.o

.PHONY : BookTutorial/AsyncThreadGroup.o

# target to build an object file
BookTutorial/AsyncThreadGroup.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/BookTutorial/AsyncThreadGroup.cpp.o
.PHONY : BookTutorial/AsyncThreadGroup.cpp.o

BookTutorial/AsyncThreadGroup.i: BookTutorial/AsyncThreadGroup.cpp.i

.PHONY : BookTutorial/AsyncThreadGroup.i

# target to preprocess a source file
BookTutorial/AsyncThreadGroup.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/BookTutorial/AsyncThreadGroup.cpp.i
.PHONY : BookTutorial/AsyncThreadGroup.cpp.i

BookTutorial/AsyncThreadGroup.s: BookTutorial/AsyncThreadGroup.cpp.s

.PHONY : BookTutorial/AsyncThreadGroup.s

# target to generate assembly for a file
BookTutorial/AsyncThreadGroup.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/BookTutorial/AsyncThreadGroup.cpp.s
.PHONY : BookTutorial/AsyncThreadGroup.cpp.s

BookTutorial/BindTutorial.o: BookTutorial/BindTutorial.cpp.o

.PHONY : BookTutorial/BindTutorial.o

# target to build an object file
BookTutorial/BindTutorial.cpp.o:
	$(MAKE) -f CMakeFiles/BindTutorial.dir/build.make CMakeFiles/BindTutorial.dir/BookTutorial/BindTutorial.cpp.o
.PHONY : BookTutorial/BindTutorial.cpp.o

BookTutorial/BindTutorial.i: BookTutorial/BindTutorial.cpp.i

.PHONY : BookTutorial/BindTutorial.i

# target to preprocess a source file
BookTutorial/BindTutorial.cpp.i:
	$(MAKE) -f CMakeFiles/BindTutorial.dir/build.make CMakeFiles/BindTutorial.dir/BookTutorial/BindTutorial.cpp.i
.PHONY : BookTutorial/BindTutorial.cpp.i

BookTutorial/BindTutorial.s: BookTutorial/BindTutorial.cpp.s

.PHONY : BookTutorial/BindTutorial.s

# target to generate assembly for a file
BookTutorial/BindTutorial.cpp.s:
	$(MAKE) -f CMakeFiles/BindTutorial.dir/build.make CMakeFiles/BindTutorial.dir/BookTutorial/BindTutorial.cpp.s
.PHONY : BookTutorial/BindTutorial.cpp.s

BookTutorial/IOService.o: BookTutorial/IOService.cpp.o

.PHONY : BookTutorial/IOService.o

# target to build an object file
BookTutorial/IOService.cpp.o:
	$(MAKE) -f CMakeFiles/IOService.dir/build.make CMakeFiles/IOService.dir/BookTutorial/IOService.cpp.o
.PHONY : BookTutorial/IOService.cpp.o

BookTutorial/IOService.i: BookTutorial/IOService.cpp.i

.PHONY : BookTutorial/IOService.i

# target to preprocess a source file
BookTutorial/IOService.cpp.i:
	$(MAKE) -f CMakeFiles/IOService.dir/build.make CMakeFiles/IOService.dir/BookTutorial/IOService.cpp.i
.PHONY : BookTutorial/IOService.cpp.i

BookTutorial/IOService.s: BookTutorial/IOService.cpp.s

.PHONY : BookTutorial/IOService.s

# target to generate assembly for a file
BookTutorial/IOService.cpp.s:
	$(MAKE) -f CMakeFiles/IOService.dir/build.make CMakeFiles/IOService.dir/BookTutorial/IOService.cpp.s
.PHONY : BookTutorial/IOService.cpp.s

BookTutorial/IOServiceWork.o: BookTutorial/IOServiceWork.cpp.o

.PHONY : BookTutorial/IOServiceWork.o

# target to build an object file
BookTutorial/IOServiceWork.cpp.o:
	$(MAKE) -f CMakeFiles/IOServiceWork.dir/build.make CMakeFiles/IOServiceWork.dir/BookTutorial/IOServiceWork.cpp.o
.PHONY : BookTutorial/IOServiceWork.cpp.o

BookTutorial/IOServiceWork.i: BookTutorial/IOServiceWork.cpp.i

.PHONY : BookTutorial/IOServiceWork.i

# target to preprocess a source file
BookTutorial/IOServiceWork.cpp.i:
	$(MAKE) -f CMakeFiles/IOServiceWork.dir/build.make CMakeFiles/IOServiceWork.dir/BookTutorial/IOServiceWork.cpp.i
.PHONY : BookTutorial/IOServiceWork.cpp.i

BookTutorial/IOServiceWork.s: BookTutorial/IOServiceWork.cpp.s

.PHONY : BookTutorial/IOServiceWork.s

# target to generate assembly for a file
BookTutorial/IOServiceWork.cpp.s:
	$(MAKE) -f CMakeFiles/IOServiceWork.dir/build.make CMakeFiles/IOServiceWork.dir/BookTutorial/IOServiceWork.cpp.s
.PHONY : BookTutorial/IOServiceWork.cpp.s

ClientServer/asynchronousclient.o: ClientServer/asynchronousclient.cpp.o

.PHONY : ClientServer/asynchronousclient.o

# target to build an object file
ClientServer/asynchronousclient.cpp.o:
	$(MAKE) -f CMakeFiles/AsynchronousClient.dir/build.make CMakeFiles/AsynchronousClient.dir/ClientServer/asynchronousclient.cpp.o
.PHONY : ClientServer/asynchronousclient.cpp.o

ClientServer/asynchronousclient.i: ClientServer/asynchronousclient.cpp.i

.PHONY : ClientServer/asynchronousclient.i

# target to preprocess a source file
ClientServer/asynchronousclient.cpp.i:
	$(MAKE) -f CMakeFiles/AsynchronousClient.dir/build.make CMakeFiles/AsynchronousClient.dir/ClientServer/asynchronousclient.cpp.i
.PHONY : ClientServer/asynchronousclient.cpp.i

ClientServer/asynchronousclient.s: ClientServer/asynchronousclient.cpp.s

.PHONY : ClientServer/asynchronousclient.s

# target to generate assembly for a file
ClientServer/asynchronousclient.cpp.s:
	$(MAKE) -f CMakeFiles/AsynchronousClient.dir/build.make CMakeFiles/AsynchronousClient.dir/ClientServer/asynchronousclient.cpp.s
.PHONY : ClientServer/asynchronousclient.cpp.s

ClientServer/challengeserver.o: ClientServer/challengeserver.cpp.o

.PHONY : ClientServer/challengeserver.o

# target to build an object file
ClientServer/challengeserver.cpp.o:
	$(MAKE) -f CMakeFiles/ChallengeServer.dir/build.make CMakeFiles/ChallengeServer.dir/ClientServer/challengeserver.cpp.o
.PHONY : ClientServer/challengeserver.cpp.o

ClientServer/challengeserver.i: ClientServer/challengeserver.cpp.i

.PHONY : ClientServer/challengeserver.i

# target to preprocess a source file
ClientServer/challengeserver.cpp.i:
	$(MAKE) -f CMakeFiles/ChallengeServer.dir/build.make CMakeFiles/ChallengeServer.dir/ClientServer/challengeserver.cpp.i
.PHONY : ClientServer/challengeserver.cpp.i

ClientServer/challengeserver.s: ClientServer/challengeserver.cpp.s

.PHONY : ClientServer/challengeserver.s

# target to generate assembly for a file
ClientServer/challengeserver.cpp.s:
	$(MAKE) -f CMakeFiles/ChallengeServer.dir/build.make CMakeFiles/ChallengeServer.dir/ClientServer/challengeserver.cpp.s
.PHONY : ClientServer/challengeserver.cpp.s

ClientServer/synchronousclient.o: ClientServer/synchronousclient.cpp.o

.PHONY : ClientServer/synchronousclient.o

# target to build an object file
ClientServer/synchronousclient.cpp.o:
	$(MAKE) -f CMakeFiles/SynchronousClient.dir/build.make CMakeFiles/SynchronousClient.dir/ClientServer/synchronousclient.cpp.o
.PHONY : ClientServer/synchronousclient.cpp.o

ClientServer/synchronousclient.i: ClientServer/synchronousclient.cpp.i

.PHONY : ClientServer/synchronousclient.i

# target to preprocess a source file
ClientServer/synchronousclient.cpp.i:
	$(MAKE) -f CMakeFiles/SynchronousClient.dir/build.make CMakeFiles/SynchronousClient.dir/ClientServer/synchronousclient.cpp.i
.PHONY : ClientServer/synchronousclient.cpp.i

ClientServer/synchronousclient.s: ClientServer/synchronousclient.cpp.s

.PHONY : ClientServer/synchronousclient.s

# target to generate assembly for a file
ClientServer/synchronousclient.cpp.s:
	$(MAKE) -f CMakeFiles/SynchronousClient.dir/build.make CMakeFiles/SynchronousClient.dir/ClientServer/synchronousclient.cpp.s
.PHONY : ClientServer/synchronousclient.cpp.s

udp_client_server/KeyProgram.o: udp_client_server/KeyProgram.cpp.o

.PHONY : udp_client_server/KeyProgram.o

# target to build an object file
udp_client_server/KeyProgram.cpp.o:
	$(MAKE) -f CMakeFiles/Booster.dir/build.make CMakeFiles/Booster.dir/udp_client_server/KeyProgram.cpp.o
.PHONY : udp_client_server/KeyProgram.cpp.o

udp_client_server/KeyProgram.i: udp_client_server/KeyProgram.cpp.i

.PHONY : udp_client_server/KeyProgram.i

# target to preprocess a source file
udp_client_server/KeyProgram.cpp.i:
	$(MAKE) -f CMakeFiles/Booster.dir/build.make CMakeFiles/Booster.dir/udp_client_server/KeyProgram.cpp.i
.PHONY : udp_client_server/KeyProgram.cpp.i

udp_client_server/KeyProgram.s: udp_client_server/KeyProgram.cpp.s

.PHONY : udp_client_server/KeyProgram.s

# target to generate assembly for a file
udp_client_server/KeyProgram.cpp.s:
	$(MAKE) -f CMakeFiles/Booster.dir/build.make CMakeFiles/Booster.dir/udp_client_server/KeyProgram.cpp.s
.PHONY : udp_client_server/KeyProgram.cpp.s

udp_client_server/UDPServer.o: udp_client_server/UDPServer.cpp.o

.PHONY : udp_client_server/UDPServer.o

# target to build an object file
udp_client_server/UDPServer.cpp.o:
	$(MAKE) -f CMakeFiles/Booster.dir/build.make CMakeFiles/Booster.dir/udp_client_server/UDPServer.cpp.o
.PHONY : udp_client_server/UDPServer.cpp.o

udp_client_server/UDPServer.i: udp_client_server/UDPServer.cpp.i

.PHONY : udp_client_server/UDPServer.i

# target to preprocess a source file
udp_client_server/UDPServer.cpp.i:
	$(MAKE) -f CMakeFiles/Booster.dir/build.make CMakeFiles/Booster.dir/udp_client_server/UDPServer.cpp.i
.PHONY : udp_client_server/UDPServer.cpp.i

udp_client_server/UDPServer.s: udp_client_server/UDPServer.cpp.s

.PHONY : udp_client_server/UDPServer.s

# target to generate assembly for a file
udp_client_server/UDPServer.cpp.s:
	$(MAKE) -f CMakeFiles/Booster.dir/build.make CMakeFiles/Booster.dir/udp_client_server/UDPServer.cpp.s
.PHONY : udp_client_server/UDPServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ChallengeServer"
	@echo "... ASIOTimers"
	@echo "... SynchronousClient"
	@echo "... ASIOExceptions"
	@echo "... ASIOTutorial"
	@echo "... rebuild_cache"
	@echo "... IOServiceWork"
	@echo "... BindTutorial"
	@echo "... IOService"
	@echo "... Booster"
	@echo "... Main"
	@echo "... AsynchronousClient"
	@echo "... BookTutorial/ASIOExceptions.o"
	@echo "... BookTutorial/ASIOExceptions.i"
	@echo "... BookTutorial/ASIOExceptions.s"
	@echo "... BookTutorial/ASIOTimers.o"
	@echo "... BookTutorial/ASIOTimers.i"
	@echo "... BookTutorial/ASIOTimers.s"
	@echo "... BookTutorial/ASIOTutorial.o"
	@echo "... BookTutorial/ASIOTutorial.i"
	@echo "... BookTutorial/ASIOTutorial.s"
	@echo "... BookTutorial/AsyncThreadGroup.o"
	@echo "... BookTutorial/AsyncThreadGroup.i"
	@echo "... BookTutorial/AsyncThreadGroup.s"
	@echo "... BookTutorial/BindTutorial.o"
	@echo "... BookTutorial/BindTutorial.i"
	@echo "... BookTutorial/BindTutorial.s"
	@echo "... BookTutorial/IOService.o"
	@echo "... BookTutorial/IOService.i"
	@echo "... BookTutorial/IOService.s"
	@echo "... BookTutorial/IOServiceWork.o"
	@echo "... BookTutorial/IOServiceWork.i"
	@echo "... BookTutorial/IOServiceWork.s"
	@echo "... ClientServer/asynchronousclient.o"
	@echo "... ClientServer/asynchronousclient.i"
	@echo "... ClientServer/asynchronousclient.s"
	@echo "... ClientServer/challengeserver.o"
	@echo "... ClientServer/challengeserver.i"
	@echo "... ClientServer/challengeserver.s"
	@echo "... ClientServer/synchronousclient.o"
	@echo "... ClientServer/synchronousclient.i"
	@echo "... ClientServer/synchronousclient.s"
	@echo "... udp_client_server/KeyProgram.o"
	@echo "... udp_client_server/KeyProgram.i"
	@echo "... udp_client_server/KeyProgram.s"
	@echo "... udp_client_server/UDPServer.o"
	@echo "... udp_client_server/UDPServer.i"
	@echo "... udp_client_server/UDPServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

